# FluxCD Kustomization source — referenced by the parent
# k8s/kustomization.yml (or by a flux Kustomization CR pointing at this dir).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecosystem

resources:
  - sealed-secret.yml
  - service.yml
  - deployment.yml

labels:
  - pairs:
      app.kubernetes.io/name: sn-translator
      app.kubernetes.io/part-of: chaos-pipeline
