---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sn-translator-credentials
  namespace: ecosystem
spec:
  encryptedData:
    SN_PASSWORD: AgASUuWa25JsydMskgwfay9mwTcYpufr4ArgvVuanX0v5qTYXwEzuYetrLXjQBvXab0LqgjtjifKfRr/4X5U6m3c4WSBBo5vsOYbb01KxAacf03dUQfqaBp7q9szuuohV6KvMfjrIgGp0BoHsMhM5L2d1AbvHSA79QLM4bD2/sbTWlqu3CL43bMCTUW/3TC52JGtteu/dznuRgQnZyilK4xW3rq85k0w7y+Z/NP+r9QoTLRaI+VZh2S2eRZ93zFVQtBxUkBPoDBcMZv3j6dJPM1YUrRnT5CGQhS9omTNPLWQPt1IMVQmMyofxFMzQozEzySVtNegOyg9gdRc+SftfifCmImt0TUiQgfaRSkiO2KpEDDhUX9jZL9EI5TGIPBML9d35gLqxm3zPqv/S1n1p9wOkTT4mLzST56Ujuf9N8otxEVM05Op7h4ZwHJHhpF0BRfpq1r/kPhlFTDCG6NFr9NQe6zjKhT4dq4JqGcWFodd+wCAb3xvsDDJDtgaBrmBpSdHFB2SMJYf8qPqRVojEd7rLTEEOuOsE9KTtUBAsjwHymAtWZZ4bP/NlOvJKdcmpRsFA3MGbmi8FYOEJ93tNwjQeHy5XgSXL/6EQYCClkIcI9HkwLHKuMyyJWU3lCyC/iy1ektUkUMj9R4rv63mRR3iApG+5Zy1oTHPjXxzqTwdEqHKg0h6AQTUQButUDfdyazjMT7aAA/79YVXFPX379vhUcJNrnj63scKln7k
    SN_USER: AgBu0/lvhZ1Bfwbcpk94yeS6I5yQbJSfLzU0OCOUEObkT+QX3MNnKRgRK9/vhjtFX9c5cFnjzbsAF/U+k++jSXQiea2VOshI8y2YhFPWiSLMI+eEiokf1GIAx/Uv2f/6p1vYjLaiDwxEXCv3zTMDl0+MYBl4AzkKGJFtpXPJlkohj3HVI/hST6CkRun6sQxr48uKeUGWnOCwWcunv4//JTjBhtvIzqnes8BCpD2squUq6yH2jmJx6pPDyB5yJck33g+UINqKa41CDgOp2dS5JrY0ii/SOg3JVs+np30k+opw47G6AMj0/qigVC4cDQP554djMxggbr2Hc44N32SeBSkx9yRSaomTuc57zf/Id75xHucDKhInT0Zectl3bA5qsKfM6MdlkImP4wP5LzAatCsDDKwK3toFBraz8p8c4pEztWezcsLYihgY+Bp2aMpB9ELszbWe4dIquSbTDOyYl+PmKLnA4Yj/411xOGep+514q//BMbsL9TlKog0mgdoAPAFVMapkohmvBz8QPujD1bNMSU9S6v7MXufOJlFjMGIl3hNFB9lwAzW9rlzoDYi/OZ7yOkDFppOZXddp1hQmAFWDdhItgFaVBYv64DL8o3fZApnSJCWVfnsj2r9ky4CKYjxlGhv+mIm1yzIXOlSrKsHNokCt1CsABMh4uVp8Uc/VQ/P5YaIbEojKveEOveOqF2tmW8nO6oqG6fI85Q==
  template:
    metadata:
      name: sn-translator-credentials
      namespace: ecosystem
